### ISSUE TITLE
Add manifest checking to CI

### ISSUE THREAD

**Issue by quantumjot** [quantumjot/BayesianTracker#156]
side-note: since you're packing data files here, you might like to add https://pypi.org/project/check-manifest/ to your CI.  Can look something like this:
```yaml
  check-manifest:
    name: Check Manifest
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
      - run: pip install check-manifest && check-manifest
```

(it requires a little [tuning of "ignores"](https://github.com/mgedmin/check-manifest#configuration) to work, but will then help avoid missing files in the wheel)

_Originally posted by @tlambert03 in https://github.com/quantumjot/BayesianTracker/issues/153#issuecomment-1155173752_
